"""MCP 도구 레이어 파사드 (live_market.py).

mcp/server.py가 이 모듈을 단일 진입점으로 사용합니다.
MCP 도구에 필요한 모든 함수/상수를 market_core + market_paths에서 re-export합니다.

내부 백엔드 코드(market.py, crawl_service.py, exchanges.py)는
market_core / paths_buy / paths_sell을 직접 import하세요.
"""
from backend.app.domain.market_core import (
    ALL_EXCHANGES,
    GLOBAL_FETCHERS,
    GROUPS,
    KOREA_FETCHERS,
    TRADING_FEES,
    WITHDRAWAL_FETCHERS,
    fetch_binance_perp,
    fetch_binance_spot,
    fetch_bitget,
    fetch_bithumb,
    fetch_coinbase,
    fetch_coinone,
    fetch_gopax,
    fetch_kraken,
    fetch_korbit,
    fetch_okx_perp,
    fetch_okx_spot,
    fetch_upbit,
    fetch_usd_krw_rate,
    get_scraped_withdrawal,
    get_withdrawal_source_url,
    enrich_ticker_fees as _enrich_ticker_fees,
    get_ticker,
    get_ticker_data as _get_ticker_data,
    get_withdrawal_data as _get_withdrawal_data,
    get_withdrawal_fees,
    list_exchanges,
)
from backend.app.domain.market_paths import (
    calculate_btc_purchase_cost,
    compare_btc_prices,
    find_cheapest_path,
    find_cheapest_path_from_snapshot_rows,
    find_cheapest_sell_path_from_snapshot_rows,
    get_exchange_summary,
    get_network_status,
)

__all__ = [
    'ALL_EXCHANGES',
    'GLOBAL_FETCHERS',
    'GROUPS',
    'KOREA_FETCHERS',
    'TRADING_FEES',
    'WITHDRAWAL_FETCHERS',
    '_enrich_ticker_fees',
    '_get_ticker_data',
    '_get_withdrawal_data',
    'calculate_btc_purchase_cost',
    'compare_btc_prices',
    'fetch_binance_perp',
    'fetch_binance_spot',
    'fetch_bitget',
    'fetch_bithumb',
    'fetch_coinbase',
    'fetch_coinone',
    'fetch_gopax',
    'fetch_kraken',
    'fetch_korbit',
    'fetch_okx_perp',
    'fetch_okx_spot',
    'fetch_upbit',
    'fetch_usd_krw_rate',
    'find_cheapest_path',
    'find_cheapest_path_from_snapshot_rows',
    'find_cheapest_sell_path_from_snapshot_rows',
    'get_exchange_summary',
    'get_network_status',
    'get_scraped_withdrawal',
    'get_ticker',
    'get_withdrawal_source_url',
    'get_withdrawal_fees',
    'list_exchanges',
]
