from __future__ import annotations

import json
import logging
from datetime import datetime, timezone

from sqlalchemy.orm import Session

from backend.app.db.models import CarfExchangeInfo
from backend.app.db.session import SessionLocal

logger = logging.getLogger(__name__)

_CARF_EXCHANGES = [
    # ── 한국 원화 거래소 ──────────────────────────────────────────────────
    {
        'id': 'upbit',
        'name': '업비트',
        'short_name': '업비트',
        'type': 'korean',
        'registered_country': '대한민국',
        'carf_group': '2027',
        'carf_data_collection_start': '2026-01-01',
        'carf_first_exchange': '2027',
        'korea_service': True,
        'korea_blocked': False,
        'korea_impact': 'high',
        'impact_detail': '한국 법인, 한국 거주자 데이터 → 2027년 상호 정보교환 대상',
        'travel_rule_korea': None,
        'travel_rule_note': None,
        'korea_user_jurisdiction': None,
        'korea_user_jurisdiction_note': None,
        'map_location': {'label': '서울 중구, 대한민국', 'latitude': 37.5665, 'longitude': 126.978, 'focusLabel': '국내 서비스 본사'},
        'sources': [],
    },
    {
        'id': 'bithumb',
        'name': '빗썸',
        'short_name': '빗썸',
        'type': 'korean',
        'registered_country': '대한민국',
        'carf_group': '2027',
        'carf_data_collection_start': '2026-01-01',
        'carf_first_exchange': '2027',
        'korea_service': True,
        'korea_blocked': False,
        'korea_impact': 'high',
        'impact_detail': '한국 법인, VASP 갱신 심사 중. CARF 보고 2026년 시작',
        'travel_rule_korea': None,
        'travel_rule_note': None,
        'korea_user_jurisdiction': None,
        'korea_user_jurisdiction_note': None,
        'map_location': {'label': '서울 강남구, 대한민국', 'latitude': 37.4979, 'longitude': 127.0276, 'focusLabel': '국내 서비스 본사'},
        'sources': [],
    },
    {
        'id': 'coinone',
        'name': '코인원',
        'short_name': '코인원',
        'type': 'korean',
        'registered_country': '대한민국',
        'carf_group': '2027',
        'carf_data_collection_start': '2026-01-01',
        'carf_first_exchange': '2027',
        'korea_service': True,
        'korea_blocked': False,
        'korea_impact': 'high',
        'impact_detail': '한국 법인, FIU 제재 심의 중이나 CARF 의무 적용',
        'travel_rule_korea': None,
        'travel_rule_note': None,
        'korea_user_jurisdiction': None,
        'korea_user_jurisdiction_note': None,
        'map_location': {'label': '서울 성동구, 대한민국', 'latitude': 37.5446, 'longitude': 127.0557, 'focusLabel': '국내 서비스 본사'},
        'sources': [],
    },
    {
        'id': 'korbit',
        'name': '코빗',
        'short_name': '코빗',
        'type': 'korean',
        'registered_country': '대한민국',
        'carf_group': '2027',
        'carf_data_collection_start': '2026-01-01',
        'carf_first_exchange': '2027',
        'korea_service': True,
        'korea_blocked': False,
        'korea_impact': 'high',
        'impact_detail': '한국 법인, VASP 갱신 승인 완료',
        'travel_rule_korea': None,
        'travel_rule_note': None,
        'korea_user_jurisdiction': None,
        'korea_user_jurisdiction_note': None,
        'map_location': {'label': '서울 강남구, 대한민국', 'latitude': 37.5183, 'longitude': 127.047, 'focusLabel': '국내 서비스 본사'},
        'sources': [],
    },
    {
        'id': 'gopax',
        'name': '고팍스',
        'short_name': '고팍스',
        'type': 'korean',
        'registered_country': '대한민국',
        'carf_group': '2027',
        'carf_data_collection_start': '2026-01-01',
        'carf_first_exchange': '2027',
        'korea_service': True,
        'korea_blocked': False,
        'korea_impact': 'high',
        'impact_detail': '한국 법인, Binance 지분 이슈로 VASP 갱신 불확실',
        'travel_rule_korea': None,
        'travel_rule_note': None,
        'korea_user_jurisdiction': None,
        'korea_user_jurisdiction_note': None,
        'map_location': {'label': '서울 마포구, 대한민국', 'latitude': 37.5563, 'longitude': 126.9236, 'focusLabel': '국내 서비스 본사'},
        'sources': [],
    },
    # ── 글로벌 거래소 ─────────────────────────────────────────────────────
    {
        'id': 'binance',
        'name': 'Binance',
        'short_name': 'Binance',
        'type': 'global',
        'registered_country': 'UAE (ADGM)',
        'carf_group': '2028',
        'carf_data_collection_start': '2027-01-01',
        'carf_first_exchange': '2028',
        'korea_service': False,
        'korea_blocked': True,
        'korea_impact': 'medium',
        'impact_detail': '한국 FIU 미등록, 앱 차단. 2026년 1월 UAE ADGM 이전 완료 — UAE CARF 2028 적용.',
        'travel_rule_korea': 'compatible',
        'travel_rule_note': 'VerifyVASP 참여 — 한국 거래소와 트래블룰 정보 교환 가능',
        'korea_user_jurisdiction': 'UAE (ADGM)',
        'korea_user_jurisdiction_note': '2026-01-05부터 Nest Exchange Ltd.(UAE ADGM) 약관 적용. 케이맨 Binance Holdings Ltd.에서 novation 완료.',
        'map_location': {'label': '아부다비, UAE', 'latitude': 24.4539, 'longitude': 54.3773, 'focusLabel': '글로벌 규제 허브 (ADGM)', 'note': '2026년 1월 5일부터 계약 법인이 케이맨 Nest Services Ltd.에서 UAE ADGM의 Nest Exchange Ltd.로 이전 완료.'},
        'sources': [
            {'label': 'Binance ADGM 전환 공식 발표 (2026-01-05)', 'url': 'https://www.binance.com/en/support/announcement/detail/f4f57a010f074dae9d34718635aba926', 'type': 'official'},
            {'label': 'ADGM FSRA: Binance 라이선스 승인 발표', 'url': 'https://www.adgm.com/media/announcements/binance-becomes-first-crypto-exchange-to-secure-a-global-license-under-adgm-framework-setting-a-new-standard-in-digital-asset-regulation', 'type': 'regulatory'},
            {'label': 'UAE CARF 서명 및 2028년 첫 교환 (Ministry of Finance)', 'url': 'https://mof.gov.ae/en/news/uae-signs-multilateral-competent-authority-agreement-on-the-automatic-exchange-of-information-under-the-crypto-asset-reporting-framework/', 'type': 'regulatory'},
        ],
    },
    {
        'id': 'okx',
        'name': 'OKX',
        'short_name': 'OKX',
        'type': 'global',
        'registered_country': '세이셸',
        'carf_group': '2028',
        'carf_data_collection_start': '2027-01-01',
        'carf_first_exchange': '2028',
        'korea_service': False,
        'korea_blocked': True,
        'korea_impact': 'low',
        'impact_detail': '한국 앱 차단. 세이셸 CARF 2028.',
        'travel_rule_korea': 'partial',
        'travel_rule_note': 'TRISA·VerifyVASP 일부 지원, 한국 차단으로 실질 미적용',
        'korea_user_jurisdiction': '세이셸',
        'korea_user_jurisdiction_note': 'Aux Cayes FinTech Co. Ltd.(세이셸) 약관 적용, EU 이용자는 OKX EU(몰타) 별도',
        'map_location': {'label': '빅토리아, 세이셸', 'latitude': -4.6191, 'longitude': 55.4513, 'focusLabel': '약관 법인 관할'},
        'sources': [
            {'label': 'OKX 이용약관 (Aux Cayes FinTech Co. Ltd., 세이셸)', 'url': 'https://www.okx.com/en/terms-of-service', 'type': 'tos'},
            {'label': '세이셸 FSA: CARF 의무 준수 지침 (2028년 첫 교환)', 'url': 'https://fsaseychelles.sc/digital-assets', 'type': 'regulatory'},
        ],
    },
    {
        'id': 'bybit',
        'name': 'Bybit',
        'short_name': 'Bybit',
        'type': 'global',
        'registered_country': 'BVI',
        'carf_group': '2028',
        'carf_data_collection_start': '2027-01-01',
        'carf_first_exchange': '2028',
        'korea_service': False,
        'korea_blocked': True,
        'korea_impact': 'low',
        'impact_detail': '한국 앱 차단. BVI CARF 2028.',
        'travel_rule_korea': 'partial',
        'travel_rule_note': '자체 Travel Rule 솔루션 보유, 한국 VerifyVASP 네트워크 미참여',
        'korea_user_jurisdiction': 'BVI',
        'korea_user_jurisdiction_note': 'Bybit Technology Limited(BVI) 약관 적용, 실질 HQ는 UAE 두바이.',
        'map_location': {'label': '두바이, UAE', 'latitude': 25.2048, 'longitude': 55.2708, 'focusLabel': '운영 허브'},
        'sources': [
            {'label': 'Bybit 이용약관 (Bybit Technology Limited, BVI)', 'url': 'https://www.bybit.com/en/terms-service/terms-of-service/', 'type': 'tos'},
        ],
    },
    {
        'id': 'bitget',
        'name': 'Bitget',
        'short_name': 'Bitget',
        'type': 'global',
        'registered_country': '세이셸',
        'carf_group': '2028',
        'carf_data_collection_start': '2027-01-01',
        'carf_first_exchange': '2028',
        'korea_service': False,
        'korea_blocked': True,
        'korea_impact': 'low',
        'impact_detail': '한국 앱스토어 차단. 세이셸 CARF 2028.',
        'travel_rule_korea': 'compatible',
        'travel_rule_note': 'VerifyVASP 참여 — 한국 거래소와 트래블룰 정보 교환 가능',
        'korea_user_jurisdiction': '세이셸',
        'korea_user_jurisdiction_note': 'Bitget Limited(세이셸) 약관 적용',
        'map_location': {'label': '빅토리아, 세이셸', 'latitude': -4.6191, 'longitude': 55.4513, 'focusLabel': '약관 법인 관할'},
        'sources': [
            {'label': 'Bitget 이용약관 (Bitget Limited, 세이셸)', 'url': 'https://www.bitget.com/en/support/articles/12560603794013', 'type': 'tos'},
        ],
    },
    {
        'id': 'kraken',
        'name': 'Kraken',
        'short_name': 'Kraken',
        'type': 'global',
        'registered_country': '미국 (와이오밍)',
        'carf_group': '2029',
        'carf_data_collection_start': None,
        'carf_first_exchange': '2029',
        'korea_service': False,
        'korea_blocked': False,
        'korea_impact': 'low',
        'impact_detail': '미국 CARF 2029. 한국 공식 서비스 미제공.',
        'travel_rule_korea': 'partial',
        'travel_rule_note': 'Travel Rule Protocol(TRP) 지원, 한국 VerifyVASP 네트워크 미참여',
        'korea_user_jurisdiction': '미국 (와이오밍)',
        'korea_user_jurisdiction_note': 'Payward Inc.(미국) 약관 적용, 한국 공식 서비스 미제공',
        'map_location': {'label': '샤이엔, 미국', 'latitude': 41.14, 'longitude': -104.8202, 'focusLabel': '주요 법인 관할'},
        'sources': [],
    },
    {
        'id': 'coinbase',
        'name': 'Coinbase',
        'short_name': 'Coinbase',
        'type': 'global',
        'registered_country': '미국 (텍사스)',
        'carf_group': '2029',
        'carf_data_collection_start': None,
        'carf_first_exchange': '2029',
        'korea_service': False,
        'korea_blocked': False,
        'korea_impact': 'low',
        'impact_detail': '미국 CARF 2029. 한국 공식 서비스 미제공.',
        'travel_rule_korea': 'partial',
        'travel_rule_note': 'Travel Rule Protocol(TRP) 지원, 한국 VerifyVASP 네트워크 미참여',
        'korea_user_jurisdiction': '미국 (텍사스)',
        'korea_user_jurisdiction_note': 'Coinbase Global, Inc.(미국 텍사스) 약관 적용. 2025-12-15 델라웨어→텍사스 재편입 완료. 한국 공식 서비스 미제공.',
        'map_location': {'label': '오스틴, 미국', 'latitude': 30.2672, 'longitude': -97.7431, 'focusLabel': '주요 법인 관할'},
        'sources': [],
    },
    {
        'id': 'bitfinex',
        'name': 'Bitfinex',
        'short_name': 'Bitfinex',
        'type': 'global',
        'registered_country': 'BVI',
        'carf_group': '2028',
        'carf_data_collection_start': '2027-01-01',
        'carf_first_exchange': '2028',
        'korea_service': False,
        'korea_blocked': False,
        'korea_impact': 'low',
        'impact_detail': 'BVI CARF 2028. 한국 공식 서비스 없음.',
        'travel_rule_korea': 'none',
        'travel_rule_note': '트래블룰 지원 미확인, CFTC 제재 이력으로 규제 리스크 높음',
        'korea_user_jurisdiction': 'BVI',
        'korea_user_jurisdiction_note': 'iFinex Inc.(BVI) 약관 적용',
        'map_location': {'label': '로드타운, BVI', 'latitude': 18.4286, 'longitude': -64.6185, 'focusLabel': '약관 법인 관할'},
        'sources': [],
    },
    {
        'id': 'kucoin',
        'name': 'KuCoin',
        'short_name': 'KuCoin',
        'type': 'global',
        'registered_country': '터크스케이커스',
        'carf_group': 'not_member',
        'carf_data_collection_start': None,
        'carf_first_exchange': None,
        'korea_service': False,
        'korea_blocked': True,
        'korea_impact': 'none',
        'impact_detail': '터크스케이커스 CARF 미가입. 한국 앱스토어 차단. CARF 사각지대.',
        'travel_rule_korea': 'none',
        'travel_rule_note': '트래블룰 미지원, DOJ $297M 합의 이력. 규제 회피 이전 이력',
        'korea_user_jurisdiction': '터크스케이커스',
        'korea_user_jurisdiction_note': 'Peken Global Ltd.(터크스케이커스) 약관 적용, CARF·트래블룰 모두 사각지대',
        'map_location': {'label': '프로비덴시알레스, 터크스케이커스', 'latitude': 21.7833, 'longitude': -72.2833, 'focusLabel': '약관 법인 관할'},
        'sources': [],
    },
    {
        'id': 'gate',
        'name': 'Gate.io',
        'short_name': 'Gate.io',
        'type': 'global',
        'registered_country': '케이맨 제도',
        'carf_group': '2027',
        'carf_data_collection_start': '2026-01-01',
        'carf_first_exchange': '2027',
        'korea_service': False,
        'korea_blocked': False,
        'korea_impact': 'high',
        'impact_detail': '케이맨 CARF 2027 적용. 한국을 서비스 제한 지역으로 약관에 명시.',
        'travel_rule_korea': 'partial',
        'travel_rule_note': 'VerifyVASP 참여 여부 불확실, 한국 제한 지역으로 실질 연동 미검증',
        'korea_user_jurisdiction': '케이맨 제도',
        'korea_user_jurisdiction_note': '한국을 서비스 제한 지역으로 약관에 명시. Gate Technology Inc.(케이맨) 약관 적용.',
        'map_location': {'label': '조지타운, 케이맨 제도', 'latitude': 19.2866, 'longitude': -81.3674, 'focusLabel': 'CARF 법인 관할'},
        'sources': [],
    },
    {
        'id': 'htx',
        'name': 'HTX (Huobi)',
        'short_name': 'HTX',
        'type': 'global',
        'registered_country': '파나마',
        'carf_group': 'not_member',
        'carf_data_collection_start': None,
        'carf_first_exchange': None,
        'korea_service': False,
        'korea_blocked': False,
        'korea_impact': 'none',
        'impact_detail': '구 세이셸 법인 2023년 말소 후 파나마 법인(Huobi Global S.A.)으로 전환. 파나마 CARF 미가입. 규제 공백 및 CARF 사각지대.',
        'travel_rule_korea': 'none',
        'travel_rule_note': '파나마 법인 전환 후 트래블룰 준수 불명확, 규제 공백 상태',
        'korea_user_jurisdiction': '파나마',
        'korea_user_jurisdiction_note': 'Huobi Global S.A.(파나마) 약관 적용. 세이셸 법인 말소로 전환. 파나마 CARF 미가입.',
        'map_location': {'label': '파나마시티, 파나마', 'latitude': 8.9936, 'longitude': -79.5197, 'focusLabel': '현 법인 관할'},
        'sources': [],
    },
]


def seed_carf_exchanges() -> None:
    db: Session = SessionLocal()
    try:
        for raw in _CARF_EXCHANGES:
            data = dict(raw)
            map_loc = data.pop('map_location', None)
            sources = data.pop('sources', [])
            data['map_location_json'] = json.dumps(map_loc, ensure_ascii=False) if map_loc else None
            data['sources_json'] = json.dumps(sources, ensure_ascii=False) if sources else None
            existing = db.get(CarfExchangeInfo, data['id'])
            if existing is None:
                db.add(CarfExchangeInfo(**data))
            else:
                for k, v in data.items():
                    setattr(existing, k, v)
                existing.updated_at = datetime.now(timezone.utc)
        db.commit()
        logger.info('CARF exchange seed complete: %d records', len(_CARF_EXCHANGES))
    except Exception:
        db.rollback()
        raise
    finally:
        db.close()
