"""add suspension fields to withdrawal_fee_snapshots"""

revision = '00dd07b8989a'
down_revision = '81c02ea00ab1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawal_fee_snapshots', sa.Column('suspension_reason', sa.String(length=256), nullable=True))
    op.add_column('withdrawal_fee_snapshots', sa.Column('suspension_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdrawal_fee_snapshots', 'suspension_message')
    op.drop_column('withdrawal_fee_snapshots', 'suspension_reason')
    # ### end Alembic commands ###
