"""add_carf_exchange_info"""

revision = '0288843b7964'
down_revision = 'c0cff33f89c6'
branch_labels = None
depends_on = None

from alembic import op  # noqa: E402
import sqlalchemy as sa  # noqa: E402



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carf_exchange_info',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('short_name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('registered_country', sa.String(length=128), nullable=True),
    sa.Column('carf_group', sa.String(length=16), nullable=False),
    sa.Column('carf_data_collection_start', sa.String(length=16), nullable=True),
    sa.Column('carf_first_exchange', sa.String(length=16), nullable=True),
    sa.Column('korea_service', sa.Boolean(), nullable=False),
    sa.Column('korea_blocked', sa.Boolean(), nullable=False),
    sa.Column('korea_impact', sa.String(length=16), nullable=False),
    sa.Column('impact_detail', sa.Text(), nullable=True),
    sa.Column('travel_rule_korea', sa.String(length=16), nullable=True),
    sa.Column('travel_rule_note', sa.Text(), nullable=True),
    sa.Column('korea_user_jurisdiction', sa.String(length=128), nullable=True),
    sa.Column('korea_user_jurisdiction_note', sa.Text(), nullable=True),
    sa.Column('map_location_json', sa.Text(), nullable=True),
    sa.Column('sources_json', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carf_exchange_info')
    # ### end Alembic commands ###
