"""add ip_address and request_type to access_logs"""

revision = '1b3b683b7439'
down_revision = '00dd07b8989a'
branch_labels = None
depends_on = None

from alembic import op  # noqa: E402
import sqlalchemy as sa  # noqa: E402



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_logs', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('access_logs', sa.Column('request_type', sa.String(length=16), server_default='visit', nullable=False))
    op.create_index(op.f('ix_access_logs_ip_address'), 'access_logs', ['ip_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_logs_ip_address'), table_name='access_logs')
    op.drop_column('access_logs', 'request_type')
    op.drop_column('access_logs', 'ip_address')
    # ### end Alembic commands ###
