"""add board posts and comments tables"""

from alembic import op
import sqlalchemy as sa

revision = '3b54494a63c3'
down_revision = '19522280241b'
branch_labels = None
depends_on = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('password_salt', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_posts_category'), 'board_posts', ['category'], unique=False)
    op.create_index(op.f('ix_board_posts_created_at'), 'board_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_board_posts_id'), 'board_posts', ['id'], unique=False)
    op.create_table('board_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('password_salt', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['board_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_comments_created_at'), 'board_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_board_comments_id'), 'board_comments', ['id'], unique=False)
    op.create_index(op.f('ix_board_comments_post_id'), 'board_comments', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_board_comments_post_id'), table_name='board_comments')
    op.drop_index(op.f('ix_board_comments_id'), table_name='board_comments')
    op.drop_index(op.f('ix_board_comments_created_at'), table_name='board_comments')
    op.drop_table('board_comments')
    op.drop_index(op.f('ix_board_posts_id'), table_name='board_posts')
    op.drop_index(op.f('ix_board_posts_created_at'), table_name='board_posts')
    op.drop_index(op.f('ix_board_posts_category'), table_name='board_posts')
    op.drop_table('board_posts')
    # ### end Alembic commands ###
