"""add min_withdrawal max_withdrawal to withdrawal_fee_snapshots"""

from alembic import op
import sqlalchemy as sa

revision = '7147ff15659b'
down_revision = 'a3308ad6580f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawal_fee_snapshots', sa.Column('min_withdrawal', sa.Float(), nullable=True))
    op.add_column('withdrawal_fee_snapshots', sa.Column('max_withdrawal', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdrawal_fee_snapshots', 'max_withdrawal')
    op.drop_column('withdrawal_fee_snapshots', 'min_withdrawal')
    # ### end Alembic commands ###
