"""add deposit status snapshots"""

from alembic import op
import sqlalchemy as sa

revision = '741332710e93'
down_revision = '3b54494a63c3'
branch_labels = None
depends_on = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposit_status_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_run_id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('coin', sa.String(length=16), nullable=False),
    sa.Column('network_label', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposit_status_snapshots_coin'), 'deposit_status_snapshots', ['coin'], unique=False)
    op.create_index(op.f('ix_deposit_status_snapshots_crawl_run_id'), 'deposit_status_snapshots', ['crawl_run_id'], unique=False)
    op.create_index(op.f('ix_deposit_status_snapshots_exchange'), 'deposit_status_snapshots', ['exchange'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deposit_status_snapshots_exchange'), table_name='deposit_status_snapshots')
    op.drop_index(op.f('ix_deposit_status_snapshots_crawl_run_id'), table_name='deposit_status_snapshots')
    op.drop_index(op.f('ix_deposit_status_snapshots_coin'), table_name='deposit_status_snapshots')
    op.drop_table('deposit_status_snapshots')
    # ### end Alembic commands ###
