"""add exchange_caution_info table"""

revision = '81c02ea00ab1'
down_revision = '23af95cab4b9'
branch_labels = None
depends_on = None

from alembic import op  # noqa: E402
import sqlalchemy as sa  # noqa: E402



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_caution_info',
    sa.Column('exchange_id', sa.String(length=32), nullable=False),
    sa.Column('group', sa.String(length=16), nullable=False),
    sa.Column('caution', sa.Boolean(), nullable=False),
    sa.Column('caution_reason', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('exchange_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange_caution_info')
    # ### end Alembic commands ###
