"""add exchange_volume_snapshots"""

# ruff: noqa: E402
revision = '84755ec9ae48'
down_revision = '0288843b7964'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_volume_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_run_id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('volume_24h_btc', sa.Float(), nullable=True),
    sa.Column('volume_24h_usd', sa.Float(), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=True),
    sa.Column('trust_rank', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_volume_snapshots_crawl_run_id'), 'exchange_volume_snapshots', ['crawl_run_id'], unique=False)
    op.create_index(op.f('ix_exchange_volume_snapshots_exchange'), 'exchange_volume_snapshots', ['exchange'], unique=False)
    op.create_index(op.f('ix_exchange_volume_snapshots_recorded_at'), 'exchange_volume_snapshots', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchange_volume_snapshots_recorded_at'), table_name='exchange_volume_snapshots')
    op.drop_index(op.f('ix_exchange_volume_snapshots_exchange'), table_name='exchange_volume_snapshots')
    op.drop_index(op.f('ix_exchange_volume_snapshots_crawl_run_id'), table_name='exchange_volume_snapshots')
    op.drop_table('exchange_volume_snapshots')
    # ### end Alembic commands ###
