"""add_direction_to_lightning_swap_fee_snapshots"""

from alembic import op
import sqlalchemy as sa

revision = 'a3308ad6580f'
down_revision = '598507520372'
branch_labels = None
depends_on = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lightning_swap_fee_snapshots', sa.Column('direction', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lightning_swap_fee_snapshots', 'direction')
    # ### end Alembic commands ###
