"""add exchange_capability_snapshots"""

from alembic import op
import sqlalchemy as sa

revision = 'c0cff33f89c6'
down_revision = '7147ff15659b'
branch_labels = None
depends_on = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_capability_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_run_id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('supports_lightning_deposit', sa.Boolean(), nullable=False),
    sa.Column('supports_lightning_withdrawal', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_capability_snapshots_crawl_run_id'), 'exchange_capability_snapshots', ['crawl_run_id'], unique=False)
    op.create_index(op.f('ix_exchange_capability_snapshots_exchange'), 'exchange_capability_snapshots', ['exchange'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchange_capability_snapshots_exchange'), table_name='exchange_capability_snapshots')
    op.drop_index(op.f('ix_exchange_capability_snapshots_crawl_run_id'), table_name='exchange_capability_snapshots')
    op.drop_table('exchange_capability_snapshots')
    # ### end Alembic commands ###
