"""add_lightning_swap_fee_snapshots"""

revision = 'd07e15a759c2'
down_revision = '0001_initial_schema'
branch_labels = None
depends_on = None

from alembic import op  # noqa: E402
import sqlalchemy as sa  # noqa: E402



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lightning_swap_fee_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_run_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=64), nullable=False),
    sa.Column('fee_pct', sa.Float(), nullable=True),
    sa.Column('fee_fixed_sat', sa.Integer(), nullable=True),
    sa.Column('min_amount_sat', sa.Integer(), nullable=True),
    sa.Column('max_amount_sat', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lightning_swap_fee_snapshots_crawl_run_id'), 'lightning_swap_fee_snapshots', ['crawl_run_id'], unique=False)
    op.create_index(op.f('ix_lightning_swap_fee_snapshots_service_name'), 'lightning_swap_fee_snapshots', ['service_name'], unique=False)
    op.create_index(op.f('ix_crawl_runs_id'), 'crawl_runs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawl_runs_id'), table_name='crawl_runs')
    op.drop_index(op.f('ix_lightning_swap_fee_snapshots_service_name'), table_name='lightning_swap_fee_snapshots')
    op.drop_index(op.f('ix_lightning_swap_fee_snapshots_crawl_run_id'), table_name='lightning_swap_fee_snapshots')
    op.drop_table('lightning_swap_fee_snapshots')
    # ### end Alembic commands ###
