"""add_kyc_config_table"""

from alembic import op
import sqlalchemy as sa

revision = 'f527d08979a4'
down_revision = '1b3b683b7439'
branch_labels = None
depends_on = None



_SEED_DATA = [
    {'key': 'boltz',          'is_kyc': False, 'note': '비수탁형 원자 스왑, KYC 없음'},
    {'key': 'boltzsubmarine', 'is_kyc': False, 'note': '비수탁형 원자 스왑, KYC 없음'},
    {'key': 'boltzmutual',    'is_kyc': False, 'note': '비수탁형 원자 스왑, KYC 없음'},
    {'key': 'bitfreeze',      'is_kyc': False, 'note': 'KYC 없음'},
    {'key': 'coinos',         'is_kyc': False, 'note': 'KYC 없음'},
    {'key': 'oksusu',         'is_kyc': False, 'note': 'KYC 없음'},
    {'key': 'walletofsatoshi','is_kyc': False, 'note': '계정 필요하나 KYC 불필요'},
    {'key': 'strike',         'is_kyc': True,  'note': '미국 규제 서비스, KYC 필요'},
]


def upgrade() -> None:
    kyc_table = op.create_table('kyc_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('is_kyc', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.bulk_insert(kyc_table, _SEED_DATA)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kyc_config')
    # ### end Alembic commands ###
